const mongoose=require('mongoose')
const patientSchema=new mongoose.Schema({
name:{
    type:String,
    required:true
},
diagnosedWith:{
    type:String,
    required:true
},
doctor:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"Doctor",
    required:true
},
age:{
    type:Number,
    required:true
},
medicalRecords:{
    type:mongoose.Schema.Types.ObjectId,
    ref:'MedicalRecords',
    required:true
},
bloodGroup:{
    type:String,
    required:true
},
gender:{
    type:String,
    enum:['M','F','O'],
    required:true
},
admittedIn:{
    type:mongoose.Schema.Types.ObjectId,
    ref:'Hospital',
    required:true
}
},{timestamps:true})
module.exports= mongoose.model("Patient",patientSchema)